Add support of Symfony 4
theodo/TheodoEvolutionLegacyWrapperBundle pull request #36
Opened 2018-11-19 13:17 UTC by maidmaid

2018-11-19 18:12 UTC, Paulmolin commented
Hello @maidmaid !

Thank you for your Pull Request. I just reactivated Travis CI, can you push on your Pull Request to make sure the build is triggered?

2018-11-19 22:28 UTC, maidmaid commented
Hello @Paulmolin, I just did it :)

2018-11-23 17:47 UTC, benja-M-1 requested changes

2018-11-23 17:47 UTC, benja-M-1 commented on composer.json
> +        "php": ">=7.1.3",
We still can support php >=5.3.3 for now. 
Can you add a OR in the version please?
```suggestion
        "php": ">=5.3.3|>=7.1.3",
```

2018-11-27 09:36 UTC, benja-M-1 commented
Hello @maidmaid :) Do you know when you will be able to update your PR?  That would be awesome to merge your PR in the week!

2018-11-27 11:58 UTC, maidmaid commented
Hi @benja-M-1, Ok, I'm gonna do it while this week :)

2018-12-02 17:53 UTC, maidmaid commented
It works. I think this PR could be ready as a first step and later, we can improve it in a second PR by making a code without deprecation notices from Symfony 4.

2018-12-02 20:22 UTC, benja-M-1 approved these changes

2018-12-02 20:23 UTC, benja-M-1 commented
Hi @maidmaid thank you very much for your help to update this bundle! I do agree, to remove deprecation notices from Symfony 4.

2018-12-02 20:23 UTC, merged